// ZK-STARK Age Verification Prover Program
// The proof generated by this program can be verified on-chain
// without revealing the age value.

use core::pedersen::pedersen;
use core::traits::Into;

/// Public inputs structure
/// These values are visible to everyone verifying the proof
#[derive(Drop, Serde)]
struct PublicInputs {
    minimum_age: u8,
    age_commitment: felt252,
    user_id: felt252,
}

/// Private inputs structure
/// These values are NEVER revealed - only known to the prover
#[derive(Drop, Serde)]
struct PrivateInputs {
    age: u8,
    salt: felt252,
}

/// Verification result
#[derive(Drop, Serde)]
struct VerificationResult {
    is_valid: felt252,
    proof_hash: felt252,
}

/// Main proving function
fn prove_age_verification(
    public_inputs: PublicInputs,
    private_inputs: PrivateInputs
) -> VerificationResult {
    // STEP 1: Verify the commitment
    // Recompute: pedersen(age, salt)
    let age_felt: felt252 = private_inputs.age.into();
    let computed_commitment = pedersen(age_felt, private_inputs.salt);
    let commitment_valid = computed_commitment == public_inputs.age_commitment;

    // STEP 2: Verify age range
    let age_valid = private_inputs.age >= public_inputs.minimum_age;

    // STEP 3: Combine both checks
    let is_valid = commitment_valid && age_valid;

    // Convert boolean to felt252 (1 or 0)
    let is_valid_felt = if is_valid {
        1
    } else {
        0
    };

    // STEP 4: Generate proof hash for audit trail
    let proof_hash = pedersen(
        public_inputs.user_id,
        pedersen(public_inputs.age_commitment, public_inputs.minimum_age.into())
    );

    VerificationResult {
        is_valid: is_valid_felt,
        proof_hash
    }
}

/// Main entry point for the Cairo program
fn main() -> VerificationResult {
    // PUBLIC INPUTS (visible to verifier)
    let public_inputs = PublicInputs {
        minimum_age: 18,
        age_commitment: 0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef,
        user_id: 0x9876543210,
    };

    let private_inputs = PrivateInputs {
        age: 25,
        salt: 0xabcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890,
    };

    prove_age_verification(public_inputs, private_inputs)
}